{
  "name": "vendorbgac-frontend",
  "version": "1.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "axios": "^1.6.7",
    "react": "^18.2.0",
    "react-cytoscapejs": "^1.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.14.1",
    "cytoscape": "^3.24.0"
  },
  "devDependencies": {
    "vite": "^5.0.0"
  }
}
